package com.example.LeaveService.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,

    INVALID_LEAVE_DATE_RANGE,
    OVERLAPPING_LEAVE_REQUEST,
    LEAVE_NOT_PENDING,
    REJECTION_REASON_REQUIRED,
    INACTIVE_EMPLOYEE,
    INVALID_LEAVE_TYPE,
    INSUFFICIENT_LEAVE_BALANCE
}