package com.hrms.leaveservice.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    INACTIVE_EMPLOYEE,
    INVALID_LEAVE_DATE_RANGE,
    INVALID_LEAVE_TYPE,
    LEAVE_NOT_PENDING,
    OVERLAPPING_LEAVE_REQUEST,
    REJECTION_REASON_REQUIRED,
    INSUFFICIENT_LEAVE_BALANCE
}