package com.hrms.reportingservice.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class ReportGenerateRequest {

    @NotBlank(message = "Report name is required")
    private String reportName;

    @NotBlank(message = "Generated by is required")
    private String generatedBy;
}