spring:
  application:
    name: reportingservice
  config:
    import: "optional:configserver:http://configserver:8888/"

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka