package com.hrms.trainingservice.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,

    INVALID_TRAINING_DATE_RANGE,
    TRAINING_NOT_OPEN_FOR_ENROLLMENT,
    TRAINING_CAPACITY_EXCEEDED,
    DEPARTMENT_NOT_ALLOWED,
    MAX_ENROLLMENTS_EXCEEDED,
    DUPLICATE_ENROLLMENT,
    ENROLLMENT_NOT_PENDING,
    REJECTION_REASON_REQUIRED,
    INVALID_ALLOWED_DEPARTMENTS,
    INVALID_TRAINING_CAPACITY,
    TRAINING_CAPACITY_LESS_THAN_APPROVED,
    TRAINING_ALREADY_CANCELLED,
    COMPLETED_TRAINING_CANNOT_BE_CANCELLED,
    INACTIVE_EMPLOYEE
}